development:
  tokbox_api: 46066312
  tokbox_secret: "827caa22b3a9b0456ed8a77e0f8a58a5e2c22057"
  tokbox_session_id: "2_MX40NTc2NTMwMn5-MTQ4NjY1MjAxNDkxNX5OY3dncmI3VXNXQU42bTBLSXFoZFp4NmF-fg"
  tokbox_token: "T1==cGFydG5lcl9pZD00NTc0NzA5MiZzaWc9YjA4N2VhMWRhZWI0NzZjNTcyNTYzNTVmY2NkNmEyOWZjMTU4MzU0MjpzZXNzaW9uX2lkPTJfTVg0ME5UYzBOekE1TW41LU1UUTROREF6TmpjeE9URXlNSDVMVVZWeFNucDVTVXRJUkZGNWRsaEVNMXB1YlVJM05WSi1mZyZjcmVhdGVfdGltZT0xNDg0MDM2NzMxJm5vbmNlPTAuNDI2NjUzOTQ5NTA5MzUzMSZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNDg0MDQwMzMw"
